baseURL = "smartassistant-unicamp.github.io/"
title = "Smart Assistant"
theme = ["ananke"]
resourceDir = "./public"

defaultContentLanguage = "en"
sectionPagesMenu = "main"
enableRobotsTXT = true

[services.googleAnalytics]
id = ''

[pagination]
pagerSize = 20

[languages.en]
contentDir = "content/en"
languageCode = 'en-US'
weight = 1
title = "Smart Assistant"

[languages.pt]
contentDir = "content/pt"
languageCode = 'pt-BR'
weight = 2
title = "Smart Assistant"

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
site_logo = "./static/img/eagle.png"